// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package sqlcgen

import (
	"context"
)

const countCategories = `-- name: CountCategories :one
SELECT count(*) FROM category
`

func (q *Queries) CountCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCategory = `-- name: GetCategory :one
SELECT category_id, name, last_update
FROM category
WHERE category_id = $1
`

func (q *Queries) GetCategory(ctx context.Context, categoryID int32) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, categoryID)
	var i Category
	err := row.Scan(&i.CategoryID, &i.Name, &i.LastUpdate)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT category_id, name, last_update
FROM category
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.CategoryID, &i.Name, &i.LastUpdate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByFilm = `-- name: ListCategoriesByFilm :many
SELECT c.category_id, c.name, c.last_update
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
WHERE fc.film_id = $1
ORDER BY c.name
`

// Returns all categories for a given film (no pagination needed, typically 1-2 categories).
func (q *Queries) ListCategoriesByFilm(ctx context.Context, filmID int32) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByFilm, filmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.CategoryID, &i.Name, &i.LastUpdate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
