// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: language.sql

package sqlcgen

import (
	"context"
)

const countLanguages = `-- name: CountLanguages :one
SELECT count(*) FROM language
`

func (q *Queries) CountLanguages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLanguages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLanguage = `-- name: GetLanguage :one
SELECT language_id, name, last_update
FROM language
WHERE language_id = $1
`

func (q *Queries) GetLanguage(ctx context.Context, languageID int32) (Language, error) {
	row := q.db.QueryRow(ctx, getLanguage, languageID)
	var i Language
	err := row.Scan(&i.LanguageID, &i.Name, &i.LastUpdate)
	return i, err
}

const listLanguages = `-- name: ListLanguages :many
SELECT language_id, name, last_update
FROM language
ORDER BY name
`

func (q *Queries) ListLanguages(ctx context.Context) ([]Language, error) {
	rows, err := q.db.Query(ctx, listLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Language{}
	for rows.Next() {
		var i Language
		if err := rows.Scan(&i.LanguageID, &i.Name, &i.LastUpdate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
