// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPayments = `-- name: CountPayments :one
SELECT count(*) FROM payment
`

func (q *Queries) CountPayments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPayments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPaymentsByCustomer = `-- name: CountPaymentsByCustomer :one
SELECT count(*) FROM payment WHERE customer_id = $1
`

func (q *Queries) CountPaymentsByCustomer(ctx context.Context, customerID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentsByCustomer, customerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPaymentsByDateRange = `-- name: CountPaymentsByDateRange :one
SELECT count(*) FROM payment
WHERE payment_date >= $1 AND payment_date < $2
`

type CountPaymentsByDateRangeParams struct {
	PaymentDate   pgtype.Timestamptz `json:"payment_date"`
	PaymentDate_2 pgtype.Timestamptz `json:"payment_date_2"`
}

func (q *Queries) CountPaymentsByDateRange(ctx context.Context, arg CountPaymentsByDateRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentsByDateRange, arg.PaymentDate, arg.PaymentDate_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPaymentsByRental = `-- name: CountPaymentsByRental :one
SELECT count(*) FROM payment WHERE rental_id = $1
`

func (q *Queries) CountPaymentsByRental(ctx context.Context, rentalID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentsByRental, rentalID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPaymentsByStaff = `-- name: CountPaymentsByStaff :one
SELECT count(*) FROM payment WHERE staff_id = $1
`

func (q *Queries) CountPaymentsByStaff(ctx context.Context, staffID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentsByStaff, staffID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payment (customer_id, staff_id, rental_id, amount, payment_date)
VALUES ($1, $2, $3, $4, now())
RETURNING payment_id, customer_id, staff_id, rental_id, amount, payment_date
`

type CreatePaymentParams struct {
	CustomerID int32          `json:"customer_id"`
	StaffID    int32          `json:"staff_id"`
	RentalID   int32          `json:"rental_id"`
	Amount     pgtype.Numeric `json:"amount"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.CustomerID,
		arg.StaffID,
		arg.RentalID,
		arg.Amount,
	)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.CustomerID,
		&i.StaffID,
		&i.RentalID,
		&i.Amount,
		&i.PaymentDate,
	)
	return i, err
}

const deletePayment = `-- name: DeletePayment :exec
DELETE FROM payment WHERE payment_id = $1
`

func (q *Queries) DeletePayment(ctx context.Context, paymentID int32) error {
	_, err := q.db.Exec(ctx, deletePayment, paymentID)
	return err
}

const getCustomerName = `-- name: GetCustomerName :one
SELECT first_name || ' ' || last_name AS full_name
FROM customer
WHERE customer_id = $1
`

func (q *Queries) GetCustomerName(ctx context.Context, customerID int32) (interface{}, error) {
	row := q.db.QueryRow(ctx, getCustomerName, customerID)
	var full_name interface{}
	err := row.Scan(&full_name)
	return full_name, err
}

const getPayment = `-- name: GetPayment :one
SELECT payment_id, customer_id, staff_id, rental_id, amount, payment_date
FROM payment
WHERE payment_id = $1
`

func (q *Queries) GetPayment(ctx context.Context, paymentID int32) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, paymentID)
	var i Payment
	err := row.Scan(
		&i.PaymentID,
		&i.CustomerID,
		&i.StaffID,
		&i.RentalID,
		&i.Amount,
		&i.PaymentDate,
	)
	return i, err
}

const getRentalDate = `-- name: GetRentalDate :one
SELECT rental_date
FROM rental
WHERE rental_id = $1
`

func (q *Queries) GetRentalDate(ctx context.Context, rentalID int32) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getRentalDate, rentalID)
	var rental_date pgtype.Timestamptz
	err := row.Scan(&rental_date)
	return rental_date, err
}

const getStaffName = `-- name: GetStaffName :one
SELECT first_name || ' ' || last_name AS full_name
FROM staff
WHERE staff_id = $1
`

func (q *Queries) GetStaffName(ctx context.Context, staffID int32) (interface{}, error) {
	row := q.db.QueryRow(ctx, getStaffName, staffID)
	var full_name interface{}
	err := row.Scan(&full_name)
	return full_name, err
}

const listPayments = `-- name: ListPayments :many
SELECT payment_id, customer_id, staff_id, rental_id, amount, payment_date
FROM payment
ORDER BY payment_date DESC, payment_id DESC
LIMIT $1 OFFSET $2
`

type ListPaymentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPayments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.PaymentID,
			&i.CustomerID,
			&i.StaffID,
			&i.RentalID,
			&i.Amount,
			&i.PaymentDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByCustomer = `-- name: ListPaymentsByCustomer :many
SELECT payment_id, customer_id, staff_id, rental_id, amount, payment_date
FROM payment
WHERE customer_id = $1
ORDER BY payment_date DESC, payment_id DESC
LIMIT $2 OFFSET $3
`

type ListPaymentsByCustomerParams struct {
	CustomerID int32 `json:"customer_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListPaymentsByCustomer(ctx context.Context, arg ListPaymentsByCustomerParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByCustomer, arg.CustomerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.PaymentID,
			&i.CustomerID,
			&i.StaffID,
			&i.RentalID,
			&i.Amount,
			&i.PaymentDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByDateRange = `-- name: ListPaymentsByDateRange :many
SELECT payment_id, customer_id, staff_id, rental_id, amount, payment_date
FROM payment
WHERE payment_date >= $1 AND payment_date < $2
ORDER BY payment_date DESC, payment_id DESC
LIMIT $3 OFFSET $4
`

type ListPaymentsByDateRangeParams struct {
	PaymentDate   pgtype.Timestamptz `json:"payment_date"`
	PaymentDate_2 pgtype.Timestamptz `json:"payment_date_2"`
	Limit         int32              `json:"limit"`
	Offset        int32              `json:"offset"`
}

func (q *Queries) ListPaymentsByDateRange(ctx context.Context, arg ListPaymentsByDateRangeParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByDateRange,
		arg.PaymentDate,
		arg.PaymentDate_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.PaymentID,
			&i.CustomerID,
			&i.StaffID,
			&i.RentalID,
			&i.Amount,
			&i.PaymentDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByRental = `-- name: ListPaymentsByRental :many
SELECT payment_id, customer_id, staff_id, rental_id, amount, payment_date
FROM payment
WHERE rental_id = $1
ORDER BY payment_date DESC, payment_id DESC
LIMIT $2 OFFSET $3
`

type ListPaymentsByRentalParams struct {
	RentalID int32 `json:"rental_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListPaymentsByRental(ctx context.Context, arg ListPaymentsByRentalParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByRental, arg.RentalID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.PaymentID,
			&i.CustomerID,
			&i.StaffID,
			&i.RentalID,
			&i.Amount,
			&i.PaymentDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByStaff = `-- name: ListPaymentsByStaff :many
SELECT payment_id, customer_id, staff_id, rental_id, amount, payment_date
FROM payment
WHERE staff_id = $1
ORDER BY payment_date DESC, payment_id DESC
LIMIT $2 OFFSET $3
`

type ListPaymentsByStaffParams struct {
	StaffID int32 `json:"staff_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListPaymentsByStaff(ctx context.Context, arg ListPaymentsByStaffParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByStaff, arg.StaffID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.PaymentID,
			&i.CustomerID,
			&i.StaffID,
			&i.RentalID,
			&i.Amount,
			&i.PaymentDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
