// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: city.sql

package sqlcgen

import (
	"context"
)

const countCities = `-- name: CountCities :one
SELECT count(*) FROM city
`

func (q *Queries) CountCities(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCities)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCity = `-- name: GetCity :one
SELECT city_id, city, country_id, last_update
FROM city
WHERE city_id = $1
`

func (q *Queries) GetCity(ctx context.Context, cityID int32) (City, error) {
	row := q.db.QueryRow(ctx, getCity, cityID)
	var i City
	err := row.Scan(
		&i.CityID,
		&i.City,
		&i.CountryID,
		&i.LastUpdate,
	)
	return i, err
}

const listCities = `-- name: ListCities :many
SELECT city_id, city, country_id, last_update
FROM city
ORDER BY city_id
LIMIT $1 OFFSET $2
`

type ListCitiesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCities(ctx context.Context, arg ListCitiesParams) ([]City, error) {
	rows, err := q.db.Query(ctx, listCities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []City{}
	for rows.Next() {
		var i City
		if err := rows.Scan(
			&i.CityID,
			&i.City,
			&i.CountryID,
			&i.LastUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
