// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: store.sql

package sqlcgen

import (
	"context"
)

const countStores = `-- name: CountStores :one
SELECT count(*) FROM store
`

func (q *Queries) CountStores(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStores)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStore = `-- name: CreateStore :one
INSERT INTO store (manager_staff_id, address_id)
VALUES ($1, $2)
RETURNING store_id, manager_staff_id, address_id, last_update
`

type CreateStoreParams struct {
	ManagerStaffID int32 `json:"manager_staff_id"`
	AddressID      int32 `json:"address_id"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, createStore, arg.ManagerStaffID, arg.AddressID)
	var i Store
	err := row.Scan(
		&i.StoreID,
		&i.ManagerStaffID,
		&i.AddressID,
		&i.LastUpdate,
	)
	return i, err
}

const deleteStore = `-- name: DeleteStore :exec
DELETE FROM store WHERE store_id = $1
`

func (q *Queries) DeleteStore(ctx context.Context, storeID int32) error {
	_, err := q.db.Exec(ctx, deleteStore, storeID)
	return err
}

const getStore = `-- name: GetStore :one
SELECT store_id, manager_staff_id, address_id, last_update
FROM store
WHERE store_id = $1
`

func (q *Queries) GetStore(ctx context.Context, storeID int32) (Store, error) {
	row := q.db.QueryRow(ctx, getStore, storeID)
	var i Store
	err := row.Scan(
		&i.StoreID,
		&i.ManagerStaffID,
		&i.AddressID,
		&i.LastUpdate,
	)
	return i, err
}

const listStores = `-- name: ListStores :many
SELECT store_id, manager_staff_id, address_id, last_update
FROM store
ORDER BY store_id
LIMIT $1 OFFSET $2
`

type ListStoresParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListStores(ctx context.Context, arg ListStoresParams) ([]Store, error) {
	rows, err := q.db.Query(ctx, listStores, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Store{}
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.StoreID,
			&i.ManagerStaffID,
			&i.AddressID,
			&i.LastUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStore = `-- name: UpdateStore :one
UPDATE store
SET manager_staff_id = $2, address_id = $3
WHERE store_id = $1
RETURNING store_id, manager_staff_id, address_id, last_update
`

type UpdateStoreParams struct {
	StoreID        int32 `json:"store_id"`
	ManagerStaffID int32 `json:"manager_staff_id"`
	AddressID      int32 `json:"address_id"`
}

func (q *Queries) UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStore, arg.StoreID, arg.ManagerStaffID, arg.AddressID)
	var i Store
	err := row.Scan(
		&i.StoreID,
		&i.ManagerStaffID,
		&i.AddressID,
		&i.LastUpdate,
	)
	return i, err
}
